baseURL = "https://berlin.juliescript.dev/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Julie en Berlín"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

googleAnalytics = "UA-177813408-1"
timeout=30000

[params]
title = "Julie in Berlin"
author = "Julieta Campos"
description = "Rating places around Berlin that I have found through TikTok"
profilePicture = "images/profile.png"
images = ["images/profile.png"]
mainSections = ["posts"]

## Social links

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/juliescript"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/juliescript"

[[params.socialIcons]]
icon = "fa-twitter"
title = "twitter"
url = "https://www.twitter.com/juliescript"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"
  